In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])

In [6]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [8]:
df.tail(2)

Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [11]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

###Indexing
###columnname,rowIndex[.loc],rowIndex columnIndex[.iloc]

In [12]:
df[['Column1']]

Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [13]:
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [14]:
df.loc[['Row3']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11

In [15]:
df.loc[['Row1','Row3']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row3        8        9       10       11

In [16]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [17]:
df.iloc[0:3,1:3]

Column2  Column3
Row1        1        2
Row2        5        6
Row3        9       10

In [18]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [19]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [20]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [21]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,4,np.nan]],index=['Row1','Row2'],columns=['Column1','Column2','Column3'])

In [48]:
df

Column1  Column2  Column3
Row1        1      NaN      2.0
Row2        1      4.0      NaN

In [50]:
df.isnull().sum()

Column1    0
Column2    1
Column3    1
dtype: int64

In [23]:
df[~df.isnull()]

Column1  Column2  Column3
Row1        1      NaN      2.0
Row2        1      4.0      NaN

In [24]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False     True

In [25]:
df['Column3'].value_counts()

Column3
2.0    1
Name: count, dtype: int64

In [26]:
df['Column1'].unique()

array([1])

In [31]:
df1=pd.DataFrame(data=[[1,2,3,4],[3,4,5,6]],index=["x","y"],columns=['a','b','c','d'])
print(df1)

   a  b  c  d
x  1  2  3  4
y  3  4  5  6
